name: Publish
permissions:
  contents: write
on:
  push:
    branches: [ "main" ]
    tags:
      - "*.*.*"
  pull_request:
    branches: [ "main" ]

jobs:

  publish:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v5

    - uses: actions/setup-node@v5
      with:
        node-version: '24'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish
      run: |
        npm version "${{ github.ref_name }}" --no-git-tag-version
        npm publish --access public --provenance
